### ISSUE TITLE
Define configuration schema

### ISSUE THREAD

**Issue by whiskeysierra** [whiskeysierra/put-it-to-rest#4]
```yaml
rest:
  oauth:
    client-id: business-partner-service
    access-token-url: ${ACCESS_TOKEN_URL:http://example.com}
    scheduling-period: 10
    timeouts:
      connect: 2
  clients:
    business-partner:
      base-url: https://business-partner-service.team.company.com
      oauth.scopes:
        - uid
        - business-partner-service.read
      timeouts:
        read: 3
    exchange-rate:
      base-url: https://exchange-rate-service.team.company.com
      oauth.scopes:
        - uid
    ecb:
      base-url: http://www.ecb.europa.eu
      oauth.enabled: false
```
